### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Pandawan** [kitsonk/deno_ls_plugin#2]
Hey, I've tried everything and I still can't get deno to work nicely with VSCode.

In tsconfig.json, I added the `deno_ls_plugin`, and added the paths for `deno`, `https://*` and `http://*`. I also added the custom typescript in settings.json's `typescript.tsdk`. 

Even with all of that, vscode still gives me the error
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

// An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/x/oak/mod' instead. ts(2691)
```

(PS: I tried generating an entirely new project using the `ameerthehacker.deno-vscode` extension. I also tried the `justjavac.vscode-deno` extension but get the same result).

I've uploaded my project in [this repository](https://github.com/PandawanFr/deno_example) if you want to test it.

**Comment by slim-hmidi** [comment]
I face the same problem here, I tried everything but nothing works. The temporary solution I use is `// @ts-ignore`.
How can I fix this issue?

**Comment by Pandawan** [comment]
Hey, I've been using [Axetroy's VSCode Deno extension](https://github.com/axetroy/vscode-deno) for a while now and have not encountered this issue. Maybe try it and see if it works for you too? (Note: with that extension, I don't think `deno_ls_plugin` is needed anymore).

**Comment by kitsonk** [comment]
Correct. I need to archive this repo.
